import { Inter } from "next/font/google";
import "./../globals.css";
import Sidebar from "../layouts/Sidebar";
import Header from "../layouts/Header";
import { ReduxProvider } from "../../redux/provider"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
      <div>
        <Header />
        <Sidebar />
      </div>
        {children}
      </ReduxProvider>
      </body>
    </html>
  );
}
