import { Inter } from "next/font/google";
import "./../globals.css";
import Sidebar from "@/app/layouts/Sidebar";
import Header from "@/app/layouts/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <div>
        <Header />
        <Sidebar />
      </div>
        {children}
      </body>
    </html>
  );
}
